// Code generated by Slice Machine. DO NOT EDIT.

import ImageGallery from './ImageGallery/index.svelte';
import NameList from './NameList/index.svelte';
import QuoteBlock from './QuoteBlock/index.svelte';
import RichText from './RichText/index.svelte';
import Spacer from './Spacer/index.svelte';
import TitleBlock from './TitleBlock/index.svelte';
import ContentWidthMedia from './ContentWidthMedia/index.svelte';

export const components = {
	image_gallery: ImageGallery,
	name_list: NameList,
	quote_block: QuoteBlock,
	rich_text: RichText,
	spacer: Spacer,
	title_block: TitleBlock,
	video_block: ContentWidthMedia
};
