// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *artist → sections*
 */
export interface ArtistDocumentDataSectionsItem {
	/**
	 * section field in *artist → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type ArtistDocumentDataSlicesSlice = never;

/**
 * Content for artist documents
 */
interface ArtistDocumentData {
	/**
	 * background image field in *artist*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * sonder presents field in *artist*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: artist.sonder_presents
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	sonder_presents: prismic.BooleanField;

	/**
	 * title field in *artist*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * sections field in *artist*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<ArtistDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *artist*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ArtistDocumentDataSlicesSlice> /**
	 * Meta Description field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: artist.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *artist*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: artist.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ArtistDocumentData>,
	'artist',
	Lang
>;

/**
 * Item in *exhibit → sections*
 */
export interface ExhibitDocumentDataSectionsItem {
	/**
	 * section field in *exhibit → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type ExhibitDocumentDataSlicesSlice = never;

/**
 * Content for exhibit documents
 */
interface ExhibitDocumentData {
	/**
	 * title field in *exhibit*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * background image field in *exhibit*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * sonder presents field in *exhibit*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: exhibit.sonder_presents
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	sonder_presents: prismic.BooleanField;

	/**
	 * sections field in *exhibit*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<ExhibitDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *exhibit*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ExhibitDocumentDataSlicesSlice> /**
	 * Meta Description field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: exhibit.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *exhibit*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: exhibit.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * exhibit document from Prismic
 *
 * - **API ID**: `exhibit`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ExhibitDocumentData>,
	'exhibit',
	Lang
>;

/**
 * Item in *intro images → images*
 */
export interface IntroImagesDocumentDataImagesItem {
	/**
	 * image field in *intro images → images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_images.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * scale (%) field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 100
	 * - **API ID Path**: intro_images.images[].scale
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	scale: prismic.NumberField;

	/**
	 * left field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0
	 * - **API ID Path**: intro_images.images[].left
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	left: prismic.NumberField;

	/**
	 * top field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0
	 * - **API ID Path**: intro_images.images[].top
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	top: prismic.NumberField;
}

/**
 * Content for intro images documents
 */
interface IntroImagesDocumentData {
	/**
	 * images field in *intro images*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_images.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<IntroImagesDocumentDataImagesItem>>;
}

/**
 * intro images document from Prismic
 *
 * - **API ID**: `intro_images`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntroImagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<IntroImagesDocumentData>,
	'intro_images',
	Lang
>;

/**
 * Item in *nav → links*
 */
export interface NavDocumentDataLinksItem {
	/**
	 * active link field in *nav → links*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].active_link
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	active_link: prismic.ImageField<never>;

	/**
	 * active color field in *nav → links*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].active_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	active_color: prismic.ColorField;

	/**
	 * link field in *nav → links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * links field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavDocumentDataLinksItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

/**
 * Item in *page → sections*
 */
export interface PageDocumentDataSectionsItem {
	/**
	 * section field in *page → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type PageDocumentDataSlicesSlice =
	| QuoteBlockSlice
	| VideoBlockSlice
	| ImageGallerySlice
	| TitleBlockSlice
	| NameListSlice
	| RichTextSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * sonder presents field in *page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: page.sonder_presents
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	sonder_presents: prismic.BooleanField;

	/**
	 * Title field in *page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * background image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * sections field in *page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<PageDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes =
	| ArtistDocument
	| ExhibitDocument
	| IntroImagesDocument
	| NavDocument
	| PageDocument;

/**
 * Primary content in *ImageGallery → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
	/**
	 * shape top field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'1' | '2'>;

	/**
	 * shape bottom field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.shape_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_bottom: prismic.SelectField<'1' | '2'>;

	/**
	 * will blur field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.will_blur
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	will_blur: prismic.BooleanField;

	/**
	 * is staggered field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.is_staggered
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_staggered: prismic.BooleanField;

	/**
	 * button bottom text field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.bottom_button_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	bottom_button_text: prismic.RichTextField;

	/**
	 * button bottom link field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.button_bottom_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_bottom_link: prismic.LinkField;
}

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
	/**
	 * image field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * subtitle field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;

	/**
	 * button text field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	button_text: prismic.RichTextField;

	/**
	 * link field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageGallerySliceDefaultPrimary>,
	Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<'image_gallery', ImageGallerySliceVariation>;

/**
 * Primary content in *NameList → Primary*
 */
export interface NameListSliceDefaultPrimary {
	/**
	 * shape top field in *NameList → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'1' | '2'>;

	/**
	 * button bottom text field in *NameList → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.button_bottom_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	button_bottom_text: prismic.RichTextField;

	/**
	 * button bottom link field in *NameList → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.button_bottom_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_bottom_link: prismic.LinkField;

	/**
	 * shape bottom field in *NameList → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.shape_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_bottom: prismic.SelectField<'1' | '2'>;
}

/**
 * Primary content in *NameList → Items*
 */
export interface NameListSliceDefaultItem {
	/**
	 * name_inactive field in *NameList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].name_inactive
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	name_inactive: prismic.ImageField<never>;

	/**
	 * name active (must be the same size) field in *NameList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].name_active
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	name_active: prismic.ImageField<never>;

	/**
	 * active color field in *NameList → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].active_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	active_color: prismic.ColorField;
}

/**
 * Default variation for NameList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NameListSliceDefaultPrimary>,
	Simplify<NameListSliceDefaultItem>
>;

/**
 * Slice variation for *NameList*
 */
type NameListSliceVariation = NameListSliceDefault;

/**
 * NameList Shared Slice
 *
 * - **API ID**: `name_list`
 * - **Description**: NameList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameListSlice = prismic.SharedSlice<'name_list', NameListSliceVariation>;

/**
 * Primary content in *QuoteBlock → Primary*
 */
export interface QuoteBlockSliceDefaultPrimary {
	/**
	 * quotation field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote_block.primary.quotation
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	quotation: prismic.RichTextField;

	/**
	 * signature field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote_block.primary.signature
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	signature: prismic.ImageField<never>;
}

/**
 * Default variation for QuoteBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<QuoteBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *QuoteBlock*
 */
type QuoteBlockSliceVariation = QuoteBlockSliceDefault;

/**
 * QuoteBlock Shared Slice
 *
 * - **API ID**: `quote_block`
 * - **Description**: QuoteBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSlice = prismic.SharedSlice<'quote_block', QuoteBlockSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceDefaultPrimary {
	/**
	 * eyebrow field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow: prismic.RichTextField;

	/**
	 * title field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * subtitle field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;

	/**
	 * button text field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	button_text: prismic.RichTextField;

	/**
	 * button link field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;
}

/**
 * Default variation for TitleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TitleBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TitleBlock*
 */
type TitleBlockSliceVariation = TitleBlockSliceDefault;

/**
 * TitleBlock Shared Slice
 *
 * - **API ID**: `title_block`
 * - **Description**: TitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSlice = prismic.SharedSlice<'title_block', TitleBlockSliceVariation>;

/**
 * Primary content in *VideoBlock → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
	/**
	 * placeholder_image field in *VideoBlock → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.placeholder_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	placeholder_image: prismic.ImageField<never>;

	/**
	 * video field in *VideoBlock → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video: prismic.EmbedField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<'video_block', VideoBlockSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ArtistDocument,
			ArtistDocumentData,
			ArtistDocumentDataSectionsItem,
			ArtistDocumentDataSlicesSlice,
			ExhibitDocument,
			ExhibitDocumentData,
			ExhibitDocumentDataSectionsItem,
			ExhibitDocumentDataSlicesSlice,
			IntroImagesDocument,
			IntroImagesDocumentData,
			IntroImagesDocumentDataImagesItem,
			NavDocument,
			NavDocumentData,
			NavDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSectionsItem,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			ImageGallerySlice,
			ImageGallerySliceDefaultPrimary,
			ImageGallerySliceDefaultItem,
			ImageGallerySliceVariation,
			ImageGallerySliceDefault,
			NameListSlice,
			NameListSliceDefaultPrimary,
			NameListSliceDefaultItem,
			NameListSliceVariation,
			NameListSliceDefault,
			QuoteBlockSlice,
			QuoteBlockSliceDefaultPrimary,
			QuoteBlockSliceVariation,
			QuoteBlockSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			TitleBlockSlice,
			TitleBlockSliceDefaultPrimary,
			TitleBlockSliceVariation,
			TitleBlockSliceDefault,
			VideoBlockSlice,
			VideoBlockSliceDefaultPrimary,
			VideoBlockSliceVariation,
			VideoBlockSliceDefault
		};
	}
}
