// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *artist → sections*
 */
export interface ArtistDocumentDataSectionsItem {
	/**
	 * section field in *artist → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type ArtistDocumentDataSlicesSlice =
	| QuoteBlockSlice
	| VideoBlockSlice
	| ImageGallerySlice
	| RichTextSlice
	| TitleBlockSlice
	| NameListSlice;

/**
 * Content for artist documents
 */
interface ArtistDocumentData {
	/**
	 * background image field in *artist*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * Full Name field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.full_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	full_name: prismic.KeyTextField;

	/**
	 * First Name field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.first_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	first_name: prismic.KeyTextField;

	/**
	 * Last Name field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.last_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	last_name: prismic.KeyTextField;

	/**
	 * title_line_one field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.title_line_one
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_one: prismic.KeyTextField;

	/**
	 * title_line_two field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.title_line_two
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_two: prismic.KeyTextField;

	/**
	 * title_line_three field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.title_line_three
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_three: prismic.KeyTextField;

	/**
	 * hover color field in *artist*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.artist_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	artist_color: prismic.ColorField;

	/**
	 * default background color field in *artist*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.default_background_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	default_background_color: prismic.ColorField;

	/**
	 * nav image field in *artist*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.nav_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	nav_image: prismic.ImageField<never>;

	/**
	 * sections field in *artist*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<ArtistDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *artist*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ArtistDocumentDataSlicesSlice> /**
	 * Meta Description field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: artist.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *artist*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artist.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *artist*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: artist.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ArtistDocumentData>,
	'artist',
	Lang
>;

/**
 * Item in *artwork → secondary images*
 */
export interface ArtworkDocumentDataSecondaryImagesItem {
	/**
	 * image field in *artwork → secondary images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.secondary_images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for artwork documents
 */
interface ArtworkDocumentData {
	/**
	 * title field in *artwork*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * artist field in *artwork*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.artist
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	artist: prismic.ContentRelationshipField<'artist'>;

	/**
	 * year field in *artwork*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	year: prismic.KeyTextField;

	/**
	 * medium field in *artwork*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.medium
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	medium: prismic.KeyTextField;

	/**
	 * dimensions field in *artwork*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.dimensions
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dimensions: prismic.KeyTextField;

	/**
	 * body field in *artwork*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * primary image field in *artwork*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.primary_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	primary_image: prismic.ImageField<never>;

	/**
	 * secondary images field in *artwork*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: artwork.secondary_images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	secondary_images: prismic.GroupField<Simplify<ArtworkDocumentDataSecondaryImagesItem>>;

	/**
	 * orientation field in *artwork*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: fit will only display primary image (no slides)
	 * - **Default Value**: landscape
	 * - **API ID Path**: artwork.orientation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	orientation: prismic.SelectField<'landscape' | 'portrait' | 'fit', 'filled'>;
}

/**
 * artwork document from Prismic
 *
 * - **API ID**: `artwork`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtworkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ArtworkDocumentData>,
	'artwork',
	Lang
>;

/**
 * Item in *exhibit → sections*
 */
export interface ExhibitDocumentDataSectionsItem {
	/**
	 * section field in *exhibit → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type ExhibitDocumentDataSlicesSlice =
	| QuoteBlockSlice
	| VideoBlockSlice
	| ImageGallerySlice
	| RichTextSlice
	| TitleBlockSlice
	| NameListSlice;

/**
 * Content for exhibit documents
 */
interface ExhibitDocumentData {
	/**
	 * dates field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.dates
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dates: prismic.KeyTextField;

	/**
	 * artist name field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.artist
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	artist: prismic.KeyTextField;

	/**
	 * title field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * title_line_one field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.title_line_one
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_one: prismic.KeyTextField;

	/**
	 * title_line_two field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.title_line_two
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_two: prismic.KeyTextField;

	/**
	 * title_line_three field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.title_line_three
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_three: prismic.KeyTextField;

	/**
	 * short description field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.short_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	short_description: prismic.KeyTextField;

	/**
	 * background image field in *exhibit*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * primary image field in *exhibit*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.primary_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	primary_image: prismic.ImageField<never>;

	/**
	 * default background color field in *exhibit*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.default_background_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	default_background_color: prismic.ColorField;

	/**
	 * sections field in *exhibit*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<ExhibitDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *exhibit*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ExhibitDocumentDataSlicesSlice> /**
	 * Meta Description field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: exhibit.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *exhibit*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: exhibit.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *exhibit*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: exhibit.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * exhibit document from Prismic
 *
 * - **API ID**: `exhibit`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ExhibitDocumentData>,
	'exhibit',
	Lang
>;

/**
 * Item in *intro images → images*
 */
export interface IntroImagesDocumentDataImagesItem {
	/**
	 * image field in *intro images → images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_images.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * scale (%) field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 100
	 * - **API ID Path**: intro_images.images[].scale
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	scale: prismic.NumberField;

	/**
	 * left field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0
	 * - **API ID Path**: intro_images.images[].left
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	left: prismic.NumberField;

	/**
	 * top field in *intro images → images*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0
	 * - **API ID Path**: intro_images.images[].top
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	top: prismic.NumberField;
}

/**
 * Content for intro images documents
 */
interface IntroImagesDocumentData {
	/**
	 * images field in *intro images*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_images.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<IntroImagesDocumentDataImagesItem>>;
}

/**
 * intro images document from Prismic
 *
 * - **API ID**: `intro_images`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntroImagesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<IntroImagesDocumentData>,
	'intro_images',
	Lang
>;

/**
 * Item in *nav → links*
 */
export interface NavDocumentDataLinksItem {
	/**
	 * active link field in *nav → links*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].active_link
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	active_link: prismic.ImageField<never>;

	/**
	 * active color field in *nav → links*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].active_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	active_color: prismic.ColorField;

	/**
	 * link field in *nav → links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * links field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavDocumentDataLinksItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

/**
 * Item in *page → sections*
 */
export interface PageDocumentDataSectionsItem {
	/**
	 * section field in *page → sections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[].section
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section: prismic.KeyTextField;
}

type PageDocumentDataSlicesSlice =
	| QuoteBlockSlice
	| VideoBlockSlice
	| ImageGallerySlice
	| TitleBlockSlice
	| NameListSlice
	| RichTextSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * dates field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.dates
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dates: prismic.KeyTextField;

	/**
	 * artist field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.artist
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	artist: prismic.KeyTextField;

	/**
	 * title line one field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title_line_one
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_one: prismic.KeyTextField;

	/**
	 * title line two field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title_line_two
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_two: prismic.KeyTextField;

	/**
	 * title line three field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title_line_three
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_line_three: prismic.KeyTextField;

	/**
	 * background image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.background_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * default background color field in *page*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.default_background_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	default_background_color: prismic.ColorField;

	/**
	 * sections field in *page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.sections[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	sections: prismic.GroupField<Simplify<PageDocumentDataSectionsItem>>;

	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes =
	| ArtistDocument
	| ArtworkDocument
	| ExhibitDocument
	| IntroImagesDocument
	| NavDocument
	| PageDocument;

/**
 * Primary content in *ImageGallery → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
	/**
	 * shape top field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6'>;

	/**
	 * gallery_eyebrow field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.gallery_eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	gallery_eyebrow: prismic.KeyTextField;

	/**
	 * will blur field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.will_blur
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	will_blur: prismic.BooleanField;

	/**
	 * isList field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.islist
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	islist: prismic.BooleanField;

	/**
	 * is staggered field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.is_staggered
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_staggered: prismic.BooleanField;

	/**
	 * sectionLabel field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: image_gallery.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * gallery_closing_text field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.gallery_closing_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	gallery_closing_text: prismic.RichTextField;

	/**
	 * button bottom text field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.button_bottom_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_bottom_text: prismic.KeyTextField;

	/**
	 * button bottom link field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.primary.button_bottom_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_bottom_link: prismic.LinkField;

	/**
	 * show more button field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.show_more_button
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	show_more_button: prismic.BooleanField;

	/**
	 * lightbox toggle field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.will_open
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	will_open: prismic.BooleanField;

	/**
	 * hide field in *ImageGallery → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_gallery.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
	/**
	 * artwork field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].artwork
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	artwork: prismic.ContentRelationshipField<'artwork'>;

	/**
	 * exhibition field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].exhibition
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	exhibition: prismic.ContentRelationshipField<'exhibit'>;

	/**
	 * piece eyebrow field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: manual
	 * - **API ID Path**: image_gallery.items[].eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * artist name field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].artist_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	artist_name: prismic.KeyTextField;

	/**
	 * image field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * subtitle Two field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].subtitle_two
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle_two: prismic.KeyTextField;

	/**
	 * button text field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * link field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageGallerySliceDefaultPrimary>,
	Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<'image_gallery', ImageGallerySliceVariation>;

/**
 * Primary content in *NameList → Primary*
 */
export interface NameListSliceDefaultPrimary {
	/**
	 * section eyebrow field in *NameList → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.section_eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_eyebrow: prismic.KeyTextField;

	/**
	 * shape top field in *NameList → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: name_list.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * button bottom link field in *NameList → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.button_bottom_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_bottom_link: prismic.LinkField;

	/**
	 * sectionLabel field in *NameList → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: name_list.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * bottom_button_text field in *NameList → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.primary.bottom_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bottom_button_text: prismic.KeyTextField;

	/**
	 * hide field in *NameList → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: name_list.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Primary content in *NameList → Items*
 */
export interface NameListSliceDefaultItem {
	/**
	 * artist field in *NameList → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].artist
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	artist: prismic.ContentRelationshipField<'artist'>;

	/**
	 * artist page field in *NameList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].artist_page
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	artist_page: prismic.LinkField;

	/**
	 * artist color field in *NameList → Items*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].artist_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	artist_color: prismic.ColorField;

	/**
	 * artist active image field in *NameList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: name_list.items[].artist_active_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	artist_active_image: prismic.ImageField<never>;
}

/**
 * Default variation for NameList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NameListSliceDefaultPrimary>,
	Simplify<NameListSliceDefaultItem>
>;

/**
 * Slice variation for *NameList*
 */
type NameListSliceVariation = NameListSliceDefault;

/**
 * NameList Shared Slice
 *
 * - **API ID**: `name_list`
 * - **Description**: NameList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameListSlice = prismic.SharedSlice<'name_list', NameListSliceVariation>;

/**
 * Primary content in *QuoteBlock → Primary*
 */
export interface QuoteBlockSliceDefaultPrimary {
	/**
	 * quotation field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote_block.primary.quotation
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	quotation: prismic.RichTextField;

	/**
	 * signature field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote_block.primary.signature
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	signature: prismic.ImageField<never>;

	/**
	 * sectionLabel field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: quote_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape top field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: quote_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3', 'filled'>;

	/**
	 * hide field in *QuoteBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: quote_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Default variation for QuoteBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<QuoteBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *QuoteBlock*
 */
type QuoteBlockSliceVariation = QuoteBlockSliceDefault;

/**
 * QuoteBlock Shared Slice
 *
 * - **API ID**: `quote_block`
 * - **Description**: QuoteBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSlice = prismic.SharedSlice<'quote_block', QuoteBlockSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;

	/**
	 * sectionLabel field in *RichText → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: rich_text.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * desktop width field in *RichText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: full
	 * - **API ID Path**: rich_text.primary.desktop_width
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	desktop_width: prismic.SelectField<'full' | '4/5' | '3/4' | '2/3' | '1/2' | '1/3', 'filled'>;

	/**
	 * slice vertical padding field in *RichText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: rich_text.primary.slice_vertical_padding
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	slice_vertical_padding: prismic.SelectField<'0' | '4' | '8' | '16' | '32', 'filled'>;

	/**
	 * button text field in *RichText → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button link field in *RichText → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * hide field in *RichText → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: rich_text.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceDefaultPrimary {
	/**
	 * eyebrow field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * body field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * desktop body width  field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: full
	 * - **API ID Path**: title_block.primary.desktop_body_width
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	desktop_body_width: prismic.SelectField<'full' | '2/3' | '1/2' | '1/3' | '1/4', 'filled'>;

	/**
	 * button_text field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button link field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * sectionLabel field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: title_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape top field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: title_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * hide field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: title_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Default variation for TitleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TitleBlockSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceTwoColumnPrimary {
	/**
	 * eyebrow field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * body field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * sectionLabel field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: title_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape top field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: title_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5', 'filled'>;

	/**
	 * read more button field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: title_block.primary.read_more_button
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	read_more_button: prismic.BooleanField;

	/**
	 * image field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * button text field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button link field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * hide field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: title_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Two Column variation for TitleBlock Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceTwoColumn = prismic.SharedSliceVariation<
	'twoColumn',
	Simplify<TitleBlockSliceTwoColumnPrimary>,
	never
>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceConnectPrimary {
	/**
	 * shape top field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: title_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * sectionLabel field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: title_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * eyebrow field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * body field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * button_text field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button_two_text field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.button_two_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_two_text: prismic.KeyTextField;

	/**
	 * instagram field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: title_block.primary.instagram
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	instagram: prismic.LinkField;

	/**
	 * hide field in *TitleBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: title_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Connect variation for TitleBlock Slice
 *
 * - **API ID**: `connect`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceConnect = prismic.SharedSliceVariation<
	'connect',
	Simplify<TitleBlockSliceConnectPrimary>,
	never
>;

/**
 * Slice variation for *TitleBlock*
 */
type TitleBlockSliceVariation =
	| TitleBlockSliceDefault
	| TitleBlockSliceTwoColumn
	| TitleBlockSliceConnect;

/**
 * TitleBlock Shared Slice
 *
 * - **API ID**: `title_block`
 * - **Description**: TitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSlice = prismic.SharedSlice<'title_block', TitleBlockSliceVariation>;

/**
 * Primary content in *ContentWidthMedia → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
	/**
	 * placeholder_image field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.placeholder_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	placeholder_image: prismic.ImageField<never>;

	/**
	 * video field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video: prismic.EmbedField;

	/**
	 * sectionLabel field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: video_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape_top field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: video_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * eyebrow field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * hide field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * video variation for ContentWidthMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoBlockSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *ContentWidthMedia → Primary*
 */
export interface VideoBlockSliceSlideshowPrimary {
	/**
	 * sectionLabel field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: video_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape_top field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: video_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * eyebrow field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * hide field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * Primary content in *ContentWidthMedia → Items*
 */
export interface VideoBlockSliceSlideshowItem {
	/**
	 * image field in *ContentWidthMedia → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * slideshow variation for ContentWidthMedia Slice
 *
 * - **API ID**: `slideshow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceSlideshow = prismic.SharedSliceVariation<
	'slideshow',
	Simplify<VideoBlockSliceSlideshowPrimary>,
	Simplify<VideoBlockSliceSlideshowItem>
>;

/**
 * Primary content in *ContentWidthMedia → Primary*
 */
export interface VideoBlockSliceImagePrimary {
	/**
	 * sectionLabel field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: video_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * image field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * shape_top field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: video_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * eyebrow field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * hide field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * image variation for ContentWidthMedia Slice
 *
 * - **API ID**: `image`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceImage = prismic.SharedSliceVariation<
	'image',
	Simplify<VideoBlockSliceImagePrimary>,
	never
>;

/**
 * Primary content in *ContentWidthMedia → Primary*
 */
export interface VideoBlockSliceEmbedPrimary {
	/**
	 * sectionLabel field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: leave blank for no id
	 * - **API ID Path**: video_block.primary.sectionLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sectionLabel: prismic.KeyTextField;

	/**
	 * shape_top field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: video_block.primary.shape_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	shape_top: prismic.SelectField<'0' | '1' | '2' | '3' | '4' | '5' | '6', 'filled'>;

	/**
	 * eyebrow field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * center point field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: GeoPoint
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_block.primary.center_point
	 * - **Documentation**: https://prismic.io/docs/field#geopoint
	 */
	center_point: prismic.GeoPointField;

	/**
	 * hide field in *ContentWidthMedia → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video_block.primary.hide
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide: prismic.BooleanField;
}

/**
 * map variation for ContentWidthMedia Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceEmbed = prismic.SharedSliceVariation<
	'embed',
	Simplify<VideoBlockSliceEmbedPrimary>,
	never
>;

/**
 * Slice variation for *ContentWidthMedia*
 */
type VideoBlockSliceVariation =
	| VideoBlockSliceDefault
	| VideoBlockSliceSlideshow
	| VideoBlockSliceImage
	| VideoBlockSliceEmbed;

/**
 * ContentWidthMedia Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<'video_block', VideoBlockSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ArtistDocument,
			ArtistDocumentData,
			ArtistDocumentDataSectionsItem,
			ArtistDocumentDataSlicesSlice,
			ArtworkDocument,
			ArtworkDocumentData,
			ArtworkDocumentDataSecondaryImagesItem,
			ExhibitDocument,
			ExhibitDocumentData,
			ExhibitDocumentDataSectionsItem,
			ExhibitDocumentDataSlicesSlice,
			IntroImagesDocument,
			IntroImagesDocumentData,
			IntroImagesDocumentDataImagesItem,
			NavDocument,
			NavDocumentData,
			NavDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSectionsItem,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			ImageGallerySlice,
			ImageGallerySliceDefaultPrimary,
			ImageGallerySliceDefaultItem,
			ImageGallerySliceVariation,
			ImageGallerySliceDefault,
			NameListSlice,
			NameListSliceDefaultPrimary,
			NameListSliceDefaultItem,
			NameListSliceVariation,
			NameListSliceDefault,
			QuoteBlockSlice,
			QuoteBlockSliceDefaultPrimary,
			QuoteBlockSliceVariation,
			QuoteBlockSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			TitleBlockSlice,
			TitleBlockSliceDefaultPrimary,
			TitleBlockSliceTwoColumnPrimary,
			TitleBlockSliceConnectPrimary,
			TitleBlockSliceVariation,
			TitleBlockSliceDefault,
			TitleBlockSliceTwoColumn,
			TitleBlockSliceConnect,
			VideoBlockSlice,
			VideoBlockSliceDefaultPrimary,
			VideoBlockSliceSlideshowPrimary,
			VideoBlockSliceSlideshowItem,
			VideoBlockSliceImagePrimary,
			VideoBlockSliceEmbedPrimary,
			VideoBlockSliceVariation,
			VideoBlockSliceDefault,
			VideoBlockSliceSlideshow,
			VideoBlockSliceImage,
			VideoBlockSliceEmbed
		};
	}
}
